name: System reports

on:
    push:
        branches: ["main"]
    pull_request:
    workflow_dispatch:


jobs:
    system-info:
        runs-on: ubuntu-latest

        steps:
            - name: Print system information
              run: |
                echo "Operating System : $(uname -s)"
                echo "Kernal version: $(uname -r)"
                date
                echo -e "Disk Usage \n$(df -h)"
            - name: Install tree
              run: |
                sudo apt-get update
                sudo apt-get install -y tree
            - name: Display Runner Directory
              run: tree -L 2 "$HOME"